#ifndef ACCEL
#define ACCEL

#include <stdint.h>
#include <nrf.h>

#include "lis2dh12_reg.h"
#include "nrf52_bitfields.h"

#define LIS2DH12_I2C_BURST_LEN 32

typedef struct ArrayList {
    uint8_t buffer[6];
} ArrayList_Type;


ArrayList_Type lis2dh12_list[LIS2DH12_I2C_BURST_LEN];
volatile static uint32_t lis2dh12_ptr;

volatile static uint8_t lis2dh12_init_seq[] = {
    LIS_REG_CTRL0_ADDR,         LIS_CTRL0_DEFAULT,         LIS_REG_TEMP_CFG_ADDR,      LIS_TEMP_CFG_DEFAULT,
    LIS_REG_CTRL1_ADDR,         LIS_CTRL1_DEFAULT,         LIS_REG_CTRL2_ADDR,         LIS_CTRL2_DEFAULT,
    LIS_REG_CTRL3_ADDR,         LIS_CTRL3_DEFAULT,         LIS_REG_CTRL4_ADDR,         LIS_CTRL4_DEFAULT,
    LIS_REG_CTRL5_ADDR,         LIS_CTRL5_DEFAULT,         LIS_REG_CTRL6_ADDR,         LIS_CTRL6_DEFAULT,
    LIS_REG_FIFO_CTRL_ADDR,     LIS_FIFO_CTRL_DEFAULT,     LIS_REG_INT1_CFG_ADDR,      LIS_INT1_CFG_DEFAULT,
    LIS_REG_INT1_THS_ADDR,      LIS_INT1_THS_DEFAULT,      LIS_REG_INT1_DURATION_ADDR, LIS_INT2_DURATION_DEFAULT,
    LIS_REG_INT2_CFG_ADDR,      LIS_INT2_CFG_DEFAULT,      LIS_REG_INT2_THS_ADDR,      LIS_INT2_THS_DEFAULT,
    LIS_REG_INT2_DURATION_ADDR, LIS_INT2_DURATION_DEFAULT, LIS_REG_CLICK_CFG_ADDR,     LIS_CLICK_CFG_DEFAULT,
    LIS_REG_CLICK_THS_ADDR,     LIS_CLICK_THS_DEFAULT,     LIS_REG_TIME_LIMIT_ADDR,    LIS_TIME_LIMIT_DEFAULT,
    LIS_REG_TIME_LATENCY_ADDR,  LIS_TIME_LATENCY_DEFAULT,  LIS_REG_TIME_WINDOW_ADDR,   LIS_TIME_WINDOW_DEFAULT,
    LIS_REG_ACT_THS_ADDR,       LIS_ACT_THS_DEFAULT,       LIS_REG_ACT_DUR_ADDR,
    LIS_ACT_DUR_DEFAULT 
};

#endif
